create table achievements (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description varchar(255) not null,
    icon varchar(255) not null,
    unlocked boolean not null,
    progress integer,
    total integer
);

create table chat_messages (
    id bigint generated by default as identity primary key,
    sender varchar(255) not null,
    collective_code varchar(255),
    text varchar(1500) not null,
    timestamp timestamp(6) not null
);

create table collectives (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    join_code varchar(255) not null,
    owner_member_id bigint not null
);

create unique index uq_collectives_join_code on collectives (join_code);

create table events (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    collective_code varchar(255),
    date date not null,
    time time(6) not null,
    type varchar(255) not null,
    organizer varchar(255) not null,
    attendees integer not null,
    description varchar(255)
);

create table expenses (
    id bigint generated by default as identity primary key,
    description varchar(255) not null,
    amount integer not null,
    paid_by varchar(255) not null,
    collective_code varchar(255),
    category varchar(255) not null,
    date date not null
);

create table expense_participants (
    expense_id bigint not null,
    member_name varchar(255) not null
);

create table invitations (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    collective_code varchar(255) not null,
    invited_by varchar(255) not null,
    created_at timestamp(6) not null,
    accepted boolean not null,
    accepted_at timestamp(6)
);

create table members (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    password_hash varchar(255),
    level integer not null,
    xp integer not null,
    collective_code varchar(255),
    status varchar(255) not null
);

create unique index uq_members_name on members (name);

create table pant_entries (
    id bigint generated by default as identity primary key,
    bottles integer not null,
    amount integer not null,
    added_by varchar(255) not null,
    collective_code varchar(255),
    date date not null
);

create table rooms (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    minutes integer not null,
    collective_id bigint
);

create table settlement_checkpoints (
    id bigint generated by default as identity primary key,
    collective_code varchar(255) not null,
    settled_by varchar(255) not null,
    last_expense_id bigint not null,
    created_at timestamp(6) not null
);

create table shopping_items (
    id bigint generated by default as identity primary key,
    item varchar(255) not null,
    added_by varchar(255) not null,
    collective_code varchar(255),
    completed boolean not null
);

create table tasks (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    assignee varchar(255) not null,
    collective_code varchar(255),
    due_date date not null,
    category varchar(255) not null,
    completed boolean not null,
    xp_awarded boolean not null,
    completed_by varchar(255),
    completed_at timestamp(6),
    xp integer not null,
    recurring boolean not null
);

alter table expense_participants
    add constraint fk_expense_participants_expense
    foreign key (expense_id) references expenses (id);

alter table rooms
    add constraint fk_rooms_collective
    foreign key (collective_id) references collectives (id);
